name: ci 
on:
  push:
    branches:
      - master 
      - main
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13.0
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - run: pip install -r requirements.txt
      - run: python main.py guide
        env:
          LLM_SERVICE: ${{ vars.LLM_SERVICE }}
          MODEL: ${{ vars.MODEL }}
          ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force